const nodemailer = require("nodemailer");
const fs = require("fs");
const path = require("path");

// ✅ Configure your email transporter
const transporter = nodemailer.createTransport({
  service: "gmail",
  auth: {
    user: "codeuday6@gmail.com", // your new sender email
    pass: "ddhp egog omuk fxro", // 🔐 paste your actual 16-character App Password
  },
});

const recipients = [
  "bhakti.dharod@idfy.com",
  "bhargavic@aissel.com",
  "bharti.negi@edifecs.com",
  "bhavana@netcore.co.in",
  "bkaklotar@diabsolut.com",
  "bhavya@supplywisdom.com",
  "bhawna@weexcel.in",
  "bhupesh.wasmatkar@verse.in",
  "biju.v@inapp.com",
  "bikram.dash@tatwa.info",
  "bindu.krishnan@ospyn.com",
  "biplob.das@izmoltd.com",
  "brij@claritusconsulting.com",
  "britto@xoxoday.com",
  "bushra.mehdi@axeno.co",
  "byju@rdalabs.com",
  "celina.joseph@extentia.com",
  "chaitanya.kanthi@smartims.com",
  "chaitanya.peeta@polygon.technology",
  "chanchal.chandiok@northgateps.com",
  "chandan@noida.interrasystems.com",
  "chandan.kashyap@mysenseinc.com",
  "chandinid@saglobal.com",
  "chandini@moolya.com",
  "chandnic@lambdatest.com",
  "chandniyadav@ucreate.co.in",
  "chandra.prakash@innoverdigital.com",
  "chandra@srivensys.com",
  "chandrashekarr@softura.com",
  "chandresh.kumar@jagrannewmedia.com",
  "charles.t@palni.com",
  "charmaine@streamoid.com",
  "cverma@fcsltd.com",
  "chetna@gokwik.co",
  "chhavi.bhatnagar@acnovate.com",
  "b.chintan@introlligent.com",
  "chirag.shah@iflair.com",
  "chitram@zconsolutions.com",
  "saurabh@caastle.com",
  "cynthia@netcore.co.in",
  "damayanti.ghosh@getvymo.com",
  "daniel.shaw@kpipartners.com",
  "dathree.javvadi@vncservices.in",
  "debashishb@interrait.com",
  "debdutta.bhowmick@atidiv.com",
  "deep.patel@ics-global.in",
  "bdeepa@zeomega.com",
  "deepa@prdxn.com",
  "deepa.makhija@gupshup.io",
  "deepa.mukherjee@esri.in",
  "deepak.babu@appviewx.com",
  "deepak.deshpande@netmagicsolutions.com",
  "deepak@uchicago.edu",
  "dkhanna@ishir.com",
  "deepak.melwani@galaxyweblinks.co.in",
  "deepak.pawar@accutech.co.in",
  "deepak@dixitindia.com",
  "shivani.khairnar@wishtreetech.com",
  "akanksha.bhisikar@amdocs.com",
  "Navni.Choudhary2@amdocs.com",
  "reema@ideausher.com",
  "paridhi.mourya@oyelabs.com",
  "tulika@vivererecuited.com",
  "rutuja_khuntale@apprely.com",
  "recruitment.srmdesigns@gmail.com",
  "mkconsultancy1624@gmail.com",
  "carrer.happywork@gmail.com",
  "Nikita@relfor.com",
  "hr@broomees.com",
  "nancy@roxiler.com",
  "anjani.gochade@roxiler.com",
  "career@roxiler.com",
  "manali.kulkarni@velotio.com",
  "isha.jain@velotio.com",
  "shukantula@monjin.com",
  "careers@velotio.com",
  "pujali.joshi@Heed.co.in",
  "anushri.guha@gmail.com",
  "akash.devre@3i-infotech.com",
  "devender1979@rediffmail.com",
  "saikiran.karuphothula@3i-infotechconsultancy.com",
  "hr@themaverics.com",
  "jaydeep.nigade@rsquaresoft.com",
  "Jayasri.Karumuri@medhatechverse.com",
  "tushar.vc@shenzyn.com",
  "ashwini.k@quesscorp.com",
  "sonia.a@shenzyn.com",
  "soumya@etek.solutions",
  "rutuja.gaikwad@acmeture.com",
  "recruitment@rectitudecs.com",
  "anjali.nathani@neerinfo.com",
  "seab@dneg.com",
  "kritika.chauhan@ibm.com",
  "swaraj.mohapatra1@ibm.com",
  "simran.tiwary@dexian.com",
  "vinman01@in.ibm.com",
  "md.izhar@ibm.com",
  "Sweta.jha2@ibm.com",
  "vishal.naithani@mylofamily.com",
  "vishal@alumnux.com",
  "vishma@litmus7.com",
  "vishnu.vardhan@bitlasoft.com",
  "varora@unifocus.com",
  "vishva.paneri@lipi.in",
  "vishwa@platform9.com",
  "vishwajit@shivaami.com",
  "vishwanath.belliappa@codecraft.co.in",
  "vithika@optimizeitsystems.com",
  "vivekj@selectsourceintl.com",
  "vivek@pacificbpo.com",
  "vivek@helius-tech.com",
  "vivek.saxena@newstechnologyservices.com",
  "viveksingh@jupitice.com",
  "vram.v@ducenit.com",
  "vyas.ramaraj@trustrace.com",
  "yasar.j@techmango.net",
  "yashika@mawaimail.com",
  "yashika@vrize.com",
  "yashpal.yadav@dynproindia.com",
  "yashwanths@blubirch.com",
  "yesha.brahmbhatt@contentstack.com",
  "yogesh.waran@sandhata.com",
  "yogita.sharma@netsmartz.com",
  "zarnatrivedi@versa-networks.com",
  "zeeshan.khan@luminescent.digita",
  "zia.alam@bluepineapple.io",
  "zubair.wani@netmagicsolutions.com",
  "zulfiqar.syed@netcore.co.in",
  "sivaprasad.ramaswamy@oracle.com",
  "raj.jha@oracle.com",
  "arivumathi.r@oracle.com",
  "varsha.sharma@oracle.com",
  "sonam.so.gupta@oracle.com",
  "pravin.muthanna@oracle.com",
  "angel.mizpha@oracle.com",
  "shashikant.joshi@oracle.com",
  "Sakshi.y.sharma@oracle.com",
  "binoy.pillai@oracle.com",
  "subhasis.ghosh@oracle.com",
  "deepthi.gummidipudi@oracle.com",
  "papiya.sarkhel@oracle.com",
  "ritik.sehgal@concentrix.com",
  "kalpana.k1@concentrix.com",
  "muznabeen.fathima@concentrix.com",
  "prince.jha@concentrix.com",
  "pallavi.khandelwal@concentrix.com",
  "swarna.premchander@concentrix.com",
  "paromita.mukherjee1@concentrix.com",
  "aradhana.verma@concentrix.com",
  "basani.kumar@concentrix.com",
  "priyanka.sharma@concentrix.com",
  "chitteti.rani@concentrix.com",
  "anandsingh.tomar@concentrix.com",
  "Alfiya.peerjade@concentrix.com",
  "kanika.garg@austere.co.in",
  "Careers@thinkitive.com",
  "khan.javed@ibm.com",
  "dipankar.naskar@ibm.com",
  "suchismita.dasgupta@ibm.com",
  "Anshul.agrawal2@ibm.com",
  "jay.dasadia@ibm.com",
  "Sanjeet.nag@ibm.com",
  "Renuka.Kulkarni@ibm.com",
  "Surabhi.suseelan@ibm.com",
  "Padma.Priya1@ibm.com",
  "Nupur.rajput1@ibm.com",
  "Nimisha.Vasudevan1@ibm.com",
  "melwyn.kirath@ibm.com",
  "Kanchan.hiwarekar1@ibm.com",
  "tirth.thakkar1@ibm.com",
  "divya.pillai1@ibm.com",
  "megha.arora2@ibm.com",
  "amita.nandi.majumdar@ibm.com",
  "raksha.sahu@austere.co.in",
  "shruti.agarwal@austere.co.in",
  "gauri.garg@austere.co.in",
  "shikhir.gupta@austere.co.in",
  "hiring@austere.co.in",
  "Sreenivas.Subramoney@intel.com",
  "ayanthx.natarajan@intel.com",
  "shah.alam.rizvi@ibm.com",
  "Ashwin.kumar@kyndryl.com",
  "jayom.dave@flipkart.com",
  "himangshu.t@flipkart.com",
  "jawed.hussain@wipro.com",
  "shivani.nagpal3@wipro.com",
  "mandeep.singh49@wipro.com",
  "Partha.Bharadwaj@wipro.com",
  "trisha.sahoo@wipro.com",
  "mayur.dulhani@wipro.com",
  "dipti.belan@wipro.com",
  "swapnil.patil31@wipro.com",
  "Shivam.kumar4@wipro.com",
  "nitin.mishra@wipro.com",
  "sarita.biswas@wipro.com",
  "RA20367930@wipro.com",
  "hitesh.kapadia@wipro.com",
  "imprita.dey@wipro.com",
  "noby.benny@wipro.com",
  "anjali.bose@wipro.com",
  "akhila.shankarabhotla@wipro.com",
  "pratibha.deshmukh@wipro.com",
  "sravani.thummala1@wipro.com",
  "krishnaveni.sompalli@wipro.com",
  "santosh.zalaki@wipro.com",
  "priyanka.choudhary@wipro.com",
  "aishna.mudgal@wipro.com",
  "bhabani.choudhury@wipro.com",
  "hr@multiqos.com",
  "hr@firstcry.com",
  "hrexe@pemawellness.com",
  "ravinder.konyala@pal.tech",
  "shireen@agilerays.com",
  "manasvi.shukla@diaspark.com",
  "megha.batham@diaspark.com",
  "mahip.pathak@diaspark.com",
  "celine.morolli@fujitsu.com",
  "careersapac@fujitsu.com",
  "Akshada.Babardesai@fujitsu.com",
  "sujata.choudhury@fujitsu.com",
  "fahad.kuravle@fujitsu.com",
  "raja.anchary@paytm.com",
  "hupesh.tiwari@paytm.com",
  "nikesh.prusty@paytm.com",
  "lovin.bhatnagar@paytm.com",
  "dilip1.madhav@paytm.com",
  "anurag5.tiwari@paytm.com",
  "himanshu1.pathak@paytm.com",
  "tanmoy.kundu@paytm.com",
  "deepak4.rai@paytm.com",
  "sujeet10.kumar@paytm.com",
  "karanshih1.chavan@paytm.com",
  "siddharthbirla@intervue.io",
  "contact@scrobits.com",
  "contact@geekyworks.com",
  "dineshgiri@binarybird.in",
  "amit.chavada@binarybird.in",
  "hr@quicsolv.com",
  "info@quicsolv.com",
  "shirankla@finagg.in",
  "career@droom.in",
  "ayush.umrao@apnamart.in",
  "paladi.bharath@peopletech.com",
  "Ritu@pw.live",
  "letsbuildit@virgio.com",
  "shivank.raghuvanshi@alktalent.in",
  "jerome@emergertech.com",
  "katyayani.kshatr@tigeranalytics.com",
  "radhika@prominentstaffing.in",
  "supriya.vijay@Lendingkart.com",
  "anirudh.j@e-solutionsinc.com",
  "drishyar@chiselontechnologies.com",
  "ajay@huquo.com",
  "career@huquo.com",
  "nithesh@northite.com",
  "info@snssquare.com",
  "hire@nextechoasis.com",
  "naveen.d@innolinktech.com",
  "hr@sixthsensesecurities.com",
  "nikitha.bangare@greaveselectricmobility.com",
  "shivani.srivastava@xceedance.com",
  "madhu@webzent.com",
  "violet@comett.in",
  "payelbiswas@webviotechnologies.com",
  "hr.admin@mrtinfotech.com",
  "productanalyticshiring@zomato.com",
  "crisma.monteiro@bixbytessolutions.com",
  "Akansha.Kumari@Aidosol.com",
  "abhishek.la@peoplefy.com",
  "anchal.karbhari@unionsystechnologies.com",
  "nandini.sharma@exlservice.com",
  "Garima@actualisation.ai",
  "chirag.jain2@bain.com",
  "meghna.bhosale@atidiv.com",
  "nikita.wankhede@facileserv.com",
  "anees.qureshi@metlife.com",
  "ankit.rana@ampf.com",
  "Prajakta.Shinde02.C@eclerx.com",
  "Lilly.Grace@conduent.com",
  "kritika.anant@ustechsolutionsinc.com",
  "mmanoj@deloitte.com",
  "swati.dhole@amdocs.com",
  "shivam.dwivedi@dcminfotech.com",
  "iti.jain@globalfpo.com",
  "madhurima.agarwal@microsave.net",
  "saloni.sharma@brainhunter.in",
  "ankita@rexera.com",
  "hr@lotechpro.in",
  "deeksha.mittal@optimumfuture.in",
  "mohit@algaeservices.co.in",
  "nitika.sabharwal@acrossassist.com",
  "Vanshika.gupta@acrossassist.com",
  "hr@zyngo.co.in",
  "thanuja@delighthr.com",
  "yukkti.khattar@careernet.in",
  "thasleema@qcentro.com",
  "daniya@qcentro.com",
  "neha.joshi@propertypistol.com",
  "Vishok.pathak@inspecthoa.com",
  "gaurav.kumar1@xpressbees.com",
  "Shivaraman_g@onwardgroup.com",
  "Balbir@vimerseit.com",
  "Pratik.Raj@marico.com",
  "lokesh.dhingra1@in.ey.com",
  "navitha.gouli@iqvia.com",
  "kamatchi.venugopal@apexon.com",
  "ameesha.yadav@white-force.in",
  "manisha.jha@naukri.com",
  "arshdeep.hr@sonavibrators.com",
  "priyankas.bbhrdcon59@biocon.com",
  "ronak.l@viralfission.com",
  "Megha@0101digitall.com",
  "ops@vagarioussolutions.com",
  "kiran@gable.io",
  "kiran@linearloop.io",
  "arvind@talenthireconsulting.in",
  "shivani@firstcalli.com",
  "p.shruti@staffingcomrade.com",
  "mansi@vimerseit.com",
  "bavithra@deltacubes.us",
  "talent.india@york.ie",
  "vidhi.thakkar@nuvama.com",
  "stomar@ocrolus.com",
  "nakul.kakkar@successive.tech",
  "careers@logisofttechinc.com",
  "hr@tbsind.com",
  "Naresh.singh@exlservice.com",
  "anshulgoel@aquissearch.com",
  "sukanya.g@smartedgesolutions.co.uk",
  "krithika.r@techwaukee.com",
  "career@minimalix.in",
  "hr@gigaopsglobal.com",
  "hr@thestrategycollective.in",
  "kiran.s@esyasoft.com",
  "padmini.kar@esyasoft.com",
  "sakshi.deshkar@growcite.in",
  "nmalakar@reynoldinfotek.com",
  "dinesh@cloudisai.com",
  "shubhendutripathi@aquissearch.com",
  "sowndhari.rajasekar@montbleu.com",
  "Greeshma.yella@accordinnovations.com",
  "uzma@brainhunter.in",
  "priyadharsanis@sagclay.in",
  "marpita@sigmoidanalytics.com",
  "bishnu.sharma@blackbuck.com",
  "udita.saxena@qdegrees.com",
  "bharatb@regenesys.net",
  "veena@zaportiv.com",
  "meeta.ghosh@xceedance.com",
  "renu.naryal@encaptechno.com",
  "hr@techanicinfotech.com",
  "juhi.sharma@antrazal.com",
  "ktanneru@innominds.com",
  "hr@crayonsys.com",
  "hemalatha@sightspectrum.com",
  "aakriti.joshi@decision-tree.com",
  "kapil.sharma@metso.com",
  "Aashish.Modak@omegahms.com",
  "jobs@malpanifoods.com",
  "Vishnu.pai@conduent.com",
  "bhavana.s@osfin.ai",
  "nuzhat.nausheen@rnf.tech",
  "chaudhary.pratima@orangemantra.in",
  "fathima.banu@netambit.net",
  "bhargavi.palli@innopark.in",
  "shivani.kukreja1@swiggy.in",
  "shruthik@novotreeminds.com",
  "abhigna@nastechglobal.in",
  "careers@zapbuild.com",
  "HR@kotiboxglobaltech.com",
  "hello@tryidoltech.com",
  "mail@monyble.com",
  "hr@driffle.com",
  "info@scientiabusiness.online",
  "hr@tasklanceai.com",
  "careers@delivergate.com",
  "eez228470@ee.iitd.ac.in",
  "careers@inclusiveminds.in",
  "rupali.dahule@workificient.com",
  "beula.nadar@hansacequity.com",
  "arnabkumar.banerjee@fujitsu.com",
  "hr@jaipurservices.com",
  "hr@imgglobalinfotech.com",
  "hr@ptiwebtech.com",
  "contact@talentturbo.us",
  "Jawahar@onedatasoftware.com",
  "jobs@aimleap.com",
  "varinder.kaur@cloudanalogy.com",
  "naresh@nagarro.com",
  "liza.jain@procol.in",
  "singh.ayushi@zomato.com",
  "prernamalik@pbpartners.com",
  "talent@ndsglobal.com",
  "TA-India@DuckerCarlisle.Com",
  "nbadar@dminc.com",
  "hr@bminfotradegroup.com",
  "tech.hr@o2h.com",
  "atulya@adda247.com",
  "shivani.venkatesh@rblbank.com",
  "jyoti.singh@collegedunia.com",
  "product.team@dhruvresearch.com",
  "sheetal_sheth@silvertouch.com",
  "astha.d@sureminds.co.in",
  "malini@softvilmedia.com",
  "karthikcs.qa@gmail.com",
  "archana.vechalekar@woliba.io",
  "Sarika.gangwar@pacificbpo.com",
  "gurdas@acmegenerics.in",
  "hr.rekhathakurilf@gmail.com",
  "deepak.kumar@fulcrumdigital.com",
  "manaswini.kopparthi@pragmaedge.com",
  "dheeraj.kumar1@kellton.com",
  "drao@nisum.com",
  "office.sikkanderabdulkhader@gmail.com",
  "shekar.cheedella@olooptech.com",
  "swathipriya@nexwave.in",
  "sairam.g@s3staff.com",
  "saikumarp@initiatefirst-is.com",
  "greeshmav@Initiatefirst-is.com",
  "sridivyaj@email.xtglobal.com",
  "sowmya.v@siriab.se",
  "chaluvadi.sowjanya@weareams.com",
  "dmsaqlain.ms@gmail.com",
  "mayuri@datamorphosis.in",
  "nidhi@cerebry.co",
  "riya.shah@cygnet-digital.com",
  "hr@micrasolution.com",
  "qat.adithya2305@gmail.com",
  "Vikas.bhat@xilligence.com",
  "anuradha.t@cognizant.com",
  "joinsmbc@opentext.com",
  "swetha@srinav.net",
  "kriti.mathur01@nagarro.com",
  "hr@nexgensis.com",
  "dhwani@gotechark.com",
  "janusha@defteam.co",
  "vivek.morey@axtria.com",
  "anushka@wuelev8.tech",
  "achowdhury@qualys.com",
  "dilip.ramamoorthy@aspiresys.com",
  "pooja.khandelwal2@wipro.com",
  "anwesha.roy@moolya.com",
  "yerva.pravallika@nuvento.com",
  "divya.dubey@accolitedigital.com",
  "mukthar@bs-infotech.com",
  "linda@bs-infotech.com",
  "sridharan@bs-infotech.com",
  "aya@impactyn.com",
  "neha.anand@w3elites.com",
  "nikita.sharma@aqmtechnologies.com",
  "career@e2msolutions.com",
  "hr20@kvstaffing.com",
  "apply@triedge.in",
  "sanket.jedhe@viraltech.in",
  "damini.hr673@webkul.in",
  "hemanth.reddy@iqgateway.com",
  "careers@pixstone.com",
  "ishwarithakur.hr@gmail.com",
  "vishwakarmat@policybazaar.com",
  "joyson@storefox.ai",
  "parul.pal@stanzaliving.com",
  "tannu.ruhela@cyberinfomines.com",
  "aruha.k@p01cglobal.com",
  "priya1.sharma@infogain.com",
  "mohammed.ayesha@codinglimits.com",
  "Chaitanya.sonavane@sodexo.com",
  "kaibalya.das@flipkart.com",
  "priyanka@admedia.com",
  "Sibtain@exasoftglobal.com",
  "vijay.sharma1@celebaltech.com",
  "parul.d@mypcot.com",
  "kavya.psnmc@gmail.com",
  "sai.surampudi@uvcyber.com",
  "v-swarnak@microsoft.com",
  "silpa.e@se-mentor.com",
  "prerna.sonankar@nsquarexperts.com",
  "Ganeshan.Namboothiri@spglobal.com",
  "sonali.gaur1@namfin.in",
  "hr@cmexpertise.com",
  "aviral.mishra@collegedunia.com",
  "Gaurang.verma@manyagroup.com",
  "anjali.bose@incruiter.com",
  "Saakshi.kashyap@grapesworldwide.com",
  "Jogebharadwaj@csventures.in",
  "investments@csventures.in",
  "shivani.tyagi@acelucid.com",
  "hr@rwit.io",
  "abhishek.ahuja@artemishospitals.com",
  "hr@betasys.ai",
  "shweta.shukla@solytics-partners.com",
  "careers@hsenidbiz.com",
  "manasa.k@adyasmartmetering.com",
  "hr@adyasmartmetering.com",
  "khariya@fluidata.co",
  "dthakkar@fluidata.co",
  "hr@hashtechy.com",
  "karthika@aegan-global.com",
  "attiya.ali@thereliablejobs.com",
  "rohan@acsconsultants.in",
  "guta.saputra@insignia.co.id",
  "putri.uswatul@insignia.co.id",
  "ika.oktavia@insignia.co.id",
  "resumes@databridgemarketresearch.com",
  "anitha.chalil@securin.io",
  "careers@evvotechnology.com",
  "admin@themlco.com",
  "ritik.shaniware@i2econsulting.com",
  "hello@humanimedia.com",
  "soumyadipta.maity@itcinfotech.com",
  "sonu.aggarwal@satyamauto.in",
  "bonvin.marie@straive.com",
  "jyoti.chhanwal@arvindfashions.com",
  "aditya.kohli@1digitalstack.ai",
  "anuj.mishra1@bankajob.com",
  "careers@appadore.com",
  "lalit@thefranchiseinsiider.com",
  "hr@fltcase.com",
  "allrecruiter@edureka.co",
  "contact@exlearntech.com",
  "info@digitaliin.com",
  "hima.bindu@sumasoft.net",
  "sriram.kanungo@aiwozo.com",
  "vrushali.salve@hansacequity.com",
  "aakansha.komatwar@forma.ai",
  "aayushi@themancompany.com",
  "soumya.singh@programming.com",
  "hrd@devtechnosys.com",
  "nishant_chadha@isb.edu",
  "sudhanshu.sharma@salaryse.com",
  "jhanvi@virtualadmins.org",
  "analyst@krystalvs.com",
  "sivaraj@techzitsolutions.com",
  "Talent@codknox.com",
  "koyel@chervic.in",
  "pragya.pandey2@bankajob.com",
  "hr@digitindus.com",
  "shruti.trimukhe@comunus.in",
  "nitin.magal@brainlabsdigital.com",
  "jigar.bhatt@navaantrix.com",
  "niharika@hirecrest.in",
  "careers@webdataguru.com",
  "adititiwari17@micamail.in",
  "subhrajit@plumhq.com",
  "punnyajain@codestax.ai",
  "srishti.walia@hindustantimes.com",
  "Tanya.sharma@rnf.tech",
  "devendra@iimdirect.com",
  "careers@timespro.com",
  "hrcommunication@eggoz.in",
  "hrlead@vibrantsolar.in",
  "samp@ciklum.com"
];

const resumePath = path.join(__dirname, "Udaysinh_kalse_CV_.pdf");
const resume = fs.readFileSync(resumePath);

const sendEmails = async () => {
  for (const email of recipients) {
    const mailOptions = {
      from: "codeuday6@gmail.com", 
      to: email,
      subject: "Proactive Frontend Developer Seeking Opportunities – Let's Connect!",
      html: `<p>Hi,</p>

<p>I hope you're doing well. My name is <b>Udaysinh Kalse</b>, and I'm reaching out to express my interest in any <b>frontend development opportunities</b> at your organization.</p>

<p>I’m a passionate Frontend Developer with <b>5 months of React.js internship experience</b>, well-versed in modern frontend technologies including <b>React.js, JavaScript, HTML/CSS, Bootstrap, Tailwind CSS</b>, and backend tools like <b>Node.js and PostgreSQL</b>. I take pride in building user-centric, responsive, and performance-optimized web interfaces.</p>

<p>Here are a few of my highlighted projects:</p>

<ul>
  <li><b>Tracker-Ur-Habit App</b> – 
    <a href="https://tracker-ur-habit-app-f4mo.vercel.app/" target="_blank">Live Demo</a>
  </li>
  <li><b>Ricoz Website Clone</b> – 
    <a href="https://taupe-piroshki-3a4020.netlify.app/" target="_blank">Live Demo</a>
  </li>
  <li><b>Book Store (Frontend Only)</b> – 
    <a href="https://book-store-gamma-flame.vercel.app/" target="_blank">Live Demo</a>
  </li>
  <li><b>Weather App</b> – 
    <a href="https://theweatherapp-livid.vercel.app/" target="_blank">Live Demo</a>
  </li>
  <li><b>To-Do List App</b> – 
    <a href="https://todo-list-fawn-omega-70.vercel.app/" target="_blank">Live Demo</a>
  </li>
  <li><b>BookStore (MERN Full Stack)</b> – 
    <a href="https://github.com/Udaykalse/MERN-Book_Shop" target="_blank">GitHub Server</a> | 
    <a href="https://github.com/Udaykalse/MERN-Book_Shop_UI" target="_blank">GitHub Client</a>
  </li>
  <li><b>AuthApp (Spring Boot + React)</b> – 
    <a href="https://github.com/Udaykalse/OAuth-Application-Backend" target="_blank">GitHub Server</a> | 
    <a href="https://github.com/Udaykalse/OAuth-Application-Frontend" target="_blank">GitHub Client</a>
  </li>
  <li><b>URL Shortener (TypeScript + React + Express)</b> – 
    <a href="https://github.com/Udaykalse/URL-Shortener-Server" target="_blank">GitHub Server</a> | 
    <a href="https://github.com/Udaykalse/url-shortner-client" target="_blank">GitHub Client</a>
  </li>
  <li><b>Live Polling System (MERN)</b> – 
    <a href="https://github.com/Udaykalse/Live-polling-system/tree/main/live-polling-backend" target="_blank">GitHub Server</a> |  
    <a href="https://github.com/Udaykalse/Live-polling-system" target="_blank">GitHub Client</a>
  </li>
</ul>

<p>I’ve attached my resume for your review. I would appreciate the opportunity to speak with you about how I can bring value to your frontend team. I’m open to interviews or technical assessments at your convenience.</p>

<p>Looking forward to hearing from you.</p>

<p>Best regards,<br><b>Udaysinh Kalse</b></p>

<p>
  📞 +91 932-599-9657 | ✉️ udaykalse123@gmail.com <br>
  <a href="https://www.linkedin.com/in/uday-kalse-5aa5862b7/" target="_blank">LinkedIn</a> | 
  <a href="https://github.com/Udaykalse" target="_blank">GitHub</a>
</p>
`,
      attachments: [
        {
          filename: "Uday_Kalse_Resume.pdf",
          content: resume,
        },
      ],
    };

    try {
      const info = await transporter.sendMail(mailOptions);
      console.log(`✅ Email sent to ${email}: ${info.response}`);
    } catch (error) {
      console.error(`❌ Error sending email to ${email}:`, error);
    }
  }
};

sendEmails();
